default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password:
  host: 127.0.0.1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

secured: &secured
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  database: virtual_studio_development

test:
  <<: *default
  database: virtual_studio_test

staging:
  <<: *default
  <<: *secured
  database: virtual_studio_staging

production:
  <<: *default
  <<: *secured
  database: virtual_studio_production
